- name: secure mysql installation
  mysql_user:
    name: root
    password: "{{ mysql_root_password }}"
    login_user: root
    login_password: ""
    host_all: yes
    check_implicit_admin: yes

- name: remove anonymous user
  mysql_user:
    name: ""
    host_all: yes
    state: absent
    login_user: root
    login_password: "{{ mysql_root_password }}"