- name: Remove test database
  mysql_db:
    name: test
    state: absent
    login_user: root
    login_password: "{{ mysql_root_password }}"

- name: Reload privileges
  mysql_db:
    name: "*.*"
    state: flush_privs
    login_user: root
    login_password: "{{ mysql_root_password }}"