---
- name: index repositories update and upgrade
  hosts: all
  pre_tasks: 
    apt:
      name: update and upgrade index repositories
      update_cache: yes
      upgrade: dist

  roles:
    - name: install basic packages.
      role: 001-basic-dependencies
    - name: install and configure apache.
      role: 002-apache
    - name: install and configure a database.
      role: 003-mysql
    - name: install php and its dependencies.
      role: 004-php
