---
- name: Index Repositories update and upgrade
  hosts: all
  pre_tasks: 
    apt:
      name: Update and upgrade Index Repositories
      update_cache: yes
      upgrade: yes

  roles:
    - name: Install Basic Packages.
      role: basic
    - name: Install and configure Apache.
      role: apache
    - name: Install and configure a Database.
      role: mysql
    - name: Install PHP and its dependencies.
      role: php
